### ISSUE TITLE
PyUSB Timeout when Reading/Writing

### ISSUE THREAD

**Issue by St0nedBone** [walac/pyusb#175]
I experience an error from a HID Device I am trying to write to. I tried to follow the tutorial but at this point I am stuck, unsure whether this is a bug or something else is wrong.
My device seems to be recognize correctly, but I can not write to it. If I print(dev) I get:
```
DEVICE ID 10c4:83b4 on Bus 001 Address 003 =================
 bLength                :   0x12 (18 bytes)
 bDescriptorType        :    0x1 Device
 bcdUSB                 :  0x110 USB 1.1
 bDeviceClass           :    0x0 Specified at interface
 bDeviceSubClass        :    0x0
 bDeviceProtocol        :    0x0
 bMaxPacketSize0        :   0x40 (64 bytes)
 idVendor               : 0x10c4
 idProduct              : 0x83b4
 bcdDevice              :    0x0 Device 0.0
 iManufacturer          :    0x1 K&S!
 iProduct               :    0x2 SRD.
 iSerialNumber          :    0x0 
 bNumConfigurations     :    0x1
  CONFIGURATION 1: 64 mA ===================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x29 (41 bytes)
   bNumInterfaces       :    0x1
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0 
   bmAttributes         :   0x80 Bus Powered
   bMaxPower            :   0x20 (64 mA)
    INTERFACE 0: Human Interface Device ====================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x1
     bInterfaceClass    :    0x3 Human Interface Device
     bInterfaceSubClass :    0x0
     bInterfaceProtocol :    0x0
     iInterface         :    0x0 
      ENDPOINT 0x81: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x1
```

Then when I try to write to the Endpoint address with dev.write(0x81, '#command') I get the error:
```
Traceback (most recent call last):
  File "./test.py", line 38, in <module>
    dev.write(0x81, "#inf")
  File "/usr/lib/python3/dist-packages/usb/core.py", line 878, in write
    self.__get_timeout(timeout)
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 778, in intr_write
    timeout)
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 856, in __write
    _check(retval)
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 552, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out
```

I followed the installation guide. OS is Ubuntu 16.04 LTS on current VirtualBox.

**Comment by walac** [comment]
For HID devices, better using [hidapi](https://pypi.python.org/pypi/hid)
