### ISSUE TITLE
usb.core.USBError: [Errno 2] Entity not found when using libusb 1.0

### ISSUE THREAD

**Issue by MartianZ** [walac/pyusb#74]
C:\Users\MartianZ\Desktop\User_Application\App>python x.py
Traceback (most recent call last):
  File "x.py", line 58, in btn_dfu_upload_clicked
    dev, config, intf = self.get_dfu_device()
  File "x.py", line 37, in get_dfu_device
    for bus in busses:
  File "C:\Python27\lib\site-packages\usb\legacy.py", line 346, in <genexpr>
    return (Bus(g) for k, g in _interop._groupby(
  File "C:\Python27\lib\site-packages\usb\legacy.py", line 340, in __init__
    self.devices = [Device(d) for d in devices]
  File "C:\Python27\lib\site-packages\usb\legacy.py", line 325, in __init__
    self.configurations = [Configuration(c) for c in dev]
  File "C:\Python27\lib\site-packages\usb\core.py", line 1022, in __iter__
    yield Configuration(self, i)
  File "C:\Python27\lib\site-packages\usb\core.py", line 548, in __init__
    configuration
  File "C:\Python27\lib\site-packages\usb\backend\libusb1.py", line 701, in get_
configuration_descriptor
    config, byref(cfg)))
  File "C:\Python27\lib\site-packages\usb\backend\libusb1.py", line 560, in _che
ck
    raise USBError(_str_error[ret], ret, _libusb_errno[ret])
usb.core.USBError: [Errno 2] Entity not found

My code is as follows:

        busses = usb.busses()
        for bus in busses:
            devices = bus.devices
            print devices

I was trying to make an old DFU python program work on Windows, my os is Windows 7 64-Bit python 2.7 and pyusb from GitHub branch. 
the backend is libusb-1.0.19, I tried the same python code on Mac OS X and it worked fine.

and I also tried the following code and it worked find, so i think it may be a legacy problem.

        b = usb.backend.libusb1.get_backend(find_library=lambda C: "\libusb-1.0.dll")
        dev = usb.core.find(backend=b, idVendor=0x0001, idProduct=0xdf11)
        dev.set_configuration()

Thank you.

**Comment by walac** [comment]
@MartianZ I could reproduce the issue here. [`libusb_get_config_descriptor`](http://libusb.sourceforge.net/api-1.0/group__desc.html#gaa635d9aec77de4895dd0896ccf001532) fails for the root hub. I guess this is due to lack of permission. Could you please check which device is raising the exception? You can do this by checking which vendor and product ids belong to the faulty device, and then look for it in the device manager.

**Comment by walac** [comment]
After debugging it, I figured out this is exactly the same problem as issue #86.
