### ISSUE TITLE
[Errno 16] Resource busy

### ISSUE THREAD

**Issue by alexroot-** [walac/pyusb#76]
Hi guys,
I'm not sure if i made a mistake...
I'm always getting this error and no solution worked for me :(
My software: Python 2.7.8, libusb 1.0.19-1 and the current PyUSB version from this rep...
I'm working on Arch Linux Arm (Raspberry Pi model B)
Her's my udev rule:
```
UBSYSTEMS=="usb", ATTRS{idVendor}=="04f2", ATTRS{idProduct}=="0402", GROUP=users", MODE="0660"
```
From https://github.com/itdaniher/WeDoMore/issues/4

And a testcode:
```
#!/usr/bin/python2

import usb.core
import usb.util
import sys

def getData():
    VENDOR_ID = 0x04f2
    PRODUCT_ID = 0x0402
    DATA_SIZE = 1
    device = usb.core.find(idVendor=VENDOR_ID, idProduct=PRODUCT_ID)
    if device is None:
        sys.exit("Could not find Keyboard")

    if device.is_kernel_driver_active(0):
        try:
                device.detach_kernel_driver(0)
                print "kernel driver detached"
        except usb.core.USBError as e:
                sys.exit("Could not detach kernel driver: %s" % str(e))
    else:
        print "no kernel driver attached"
    try:
        usb.util.claim_interface(device, 0)
        print "claimed device"
    except:
        sys.exit("Could not claim the device: %s" % str(e))
    try:
        device.set_configuration()
        device.reset()
    except usb.core.USBError as e:
        sys.exit("Could not set configuration: %s" % str(e))
```
When I execute my script:
```
$sudo python2 ./test.py
no kernel driver attached
claimed device
Could not set configuration: [Errno 16] Resource busy
```

Can you tell me whats wrong?
Thanks :)

**Comment by walac** [comment]
@alexroot- Any conclusion on this issue?

**Comment by charlesreid1** [comment]
Hi @walac and @alexroot- , I came upon this thread when I experienced the same problem. When I ran with PYUSB_DEBUG set, I saw this:

```
$ python scale.py
2015-02-04 04:15:33,588 ERROR:usb.backend.libusb1:Error loading libusb 1.0 backend
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 880, in get_backend
    _setup_prototypes(_lib)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 453, in _setup_prototypes
    lib.libusb_strerror.argtypes = [c_uint]
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/arm-linux-gnueabihf/libusb-1.0.so.0: undefined symbol: libusb_strerror
```

This was using the version of libusb installed from the aptitude repositories. I removed that, installed libusb from source, and uninstalled/reinstalled pyusb, only to see the exact same error message with the new library:

```
$ python scale.py
2015-02-04 04:54:15,614 ERROR:usb.backend.libusb1:Error loading libusb 1.0 backend
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 880, in get_backend
    _setup_prototypes(_lib)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 453, in _setup_prototypes
    lib.libusb_strerror.argtypes = [c_uint]
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/libusb-1.0.so.0: undefined symbol: libusb_strerror
```

Not sure what to do now, except keep digging.

**Comment by walac** [comment]
This `libusb_strerror` was fixed in commit c46563c6b54acb9c2cb. Futhermore, you must be using a very old libusb version, because the `libusb_strerror` function was introduced a long time ago.

**Comment by charlesreid1** [comment]
Yeah, I found out (from you, actually) there were two versions of libusb floating around - [https://github.com/walac/pyusb/issues/57](this thread):

> Oh, that libusb... For reasons I am not in position to explain, we now have two libusb's. I will work on a patch for that. In the mean time, you can try this libusb.

I used that libusb, which was on Github, and installed it from source, and reinstalled PyUSB. Everything worked out after doing that.

**Comment by walac** [comment]
@charlesreid1 When you got the *undefined symbol* error, were you using lastest PyUSB git version?

**Comment by charlesreid1** [comment]
Yes, I was using a version of PyUSB installed using ```pip install --pre pyusb``` when I saw the undefined symbol error. (Also, this is the same version that is now working for me.)

**Comment by hediented** [comment]
I was using the same code to try to read from my device and when i ran my script i got : 
```
no kernel driver attached
Could not claim the device
```
and if i try to run 
```
endpoint = device[0][(0,0)][0]
data = device.read(endpoint.bEndpointAddress,0x0040)
```
i get  *resource busy error*.  I am really a beginner in this so i would really appreciate some advice on what to do next.

**Comment by walac** [comment]
Could you please generate logs (`export PYUSB_DEBUG=debug`) and post them?

**Comment by hediented** [comment]
First I want to thank you for a quick response and you help.

So this is the code I am using:
```python
import usb.core
import usb.util
import sys



VENDOR_ID = 0x22cd
PRODUCT_ID = 0x000
DATA_SIZE = 0x0040
device = usb.core.find(idVendor=VENDOR_ID, idProduct=PRODUCT_ID)
if device is None:
        sys.exit("Could not find device")

if device.is_kernel_driver_active(0):
        try:
		device.detach_kernel_driver(0)
                print "kernel driver detached"
        except usb.core.USBError as e:
                sys.exit("Could not detach kernel driver: ")
else:
        print "no kernel driver attached"


  	try:
        	usb.util.claim_interface(device, 0)
        	print "claimed device"
	except:
        	endpoint = device[0][(0,0)][0]
		data = device.read(endpoint.bEndpointAddress,0x0040)
```

And this is my log file:
```
2015-05-22 19:11:45,351 DEBUG:usb.backend.libusb1:_LibUSB.__init__(<CDLL 'libusb-1.0.so.0', handle 1d48010 at 7fef41e06210>)
2015-05-22 19:11:45,356 INFO:usb.core:find(): using backend "usb.backend.libusb1"
2015-05-22 19:11:45,356 DEBUG:usb.backend.libusb1:_LibUSB.enumerate_devices()
2015-05-22 19:11:45,356 DEBUG:usb.backend.libusb1:_LibUSB.get_device_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06990>)
2015-05-22 19:11:45,357 DEBUG:usb.backend.libusb1:_LibUSB.get_device_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>)
2015-05-22 19:11:45,357 DEBUG:usb.backend.libusb1:_LibUSB.open_device(<usb.backend.libusb1._Device object at 0x7fef41e06a90>)
2015-05-22 19:11:45,358 DEBUG:usb.backend.libusb1:_LibUSB.is_kernel_driver_active(<usb.backend.libusb1._DeviceHandle object at 0x7fef4244df10>, 0)
2015-05-22 19:11:45,358 DEBUG:usb.backend.libusb1:_LibUSB.claim_interface(<usb.backend.libusb1._DeviceHandle object at 0x7fef4244df10>, 0)
2015-05-22 19:11:45,358 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0)
2015-05-22 19:11:45,359 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0, 0, 0)
2015-05-22 19:11:45,359 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0)
2015-05-22 19:11:45,359 DEBUG:usb.backend.libusb1:_LibUSB.get_endpoint_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0, 0, 0, 0)
2015-05-22 19:11:45,359 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0, 0, 0)
2015-05-22 19:11:45,359 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0)
2015-05-22 19:11:45,359 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration(<usb.backend.libusb1._DeviceHandle object at 0x7fef4244df10>)
2015-05-22 19:11:45,359 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0)
2015-05-22 19:11:45,360 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0, 0, 0)
2015-05-22 19:11:45,360 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0)
2015-05-22 19:11:45,360 DEBUG:usb.backend.libusb1:_LibUSB.get_endpoint_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0, 0, 0, 0)
2015-05-22 19:11:45,360 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0, 0, 0)
2015-05-22 19:11:45,360 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0)
2015-05-22 19:11:45,360 DEBUG:usb.backend.libusb1:_LibUSB.claim_interface(<usb.backend.libusb1._DeviceHandle object at 0x7fef4244df10>, 0)
```

**Comment by hediented** [comment]
First I want to thank you for a quick response and you help.

So this is the code I am using:
```python
import usb.core
import usb.util
import sys



VENDOR_ID = 0x22cd
PRODUCT_ID = 0x000
DATA_SIZE = 0x0040
device = usb.core.find(idVendor=VENDOR_ID, idProduct=PRODUCT_ID)
if device is None:
        sys.exit("Could not find device")

if device.is_kernel_driver_active(0):
        try:
		device.detach_kernel_driver(0)
                print "kernel driver detached"
        except usb.core.USBError as e:
                sys.exit("Could not detach kernel driver: ")
else:
        print "no kernel driver attached"


  	try:
        	usb.util.claim_interface(device, 0)
        	print "claimed device"
	except:
        	endpoint = device[0][(0,0)][0]
		data = device.read(endpoint.bEndpointAddress,0x0040)
```

And this is my log file:
```
2015-05-22 19:11:45,351 DEBUG:usb.backend.libusb1:_LibUSB.__init__(<CDLL 'libusb-1.0.so.0', handle 1d48010 at 7fef41e06210>)
2015-05-22 19:11:45,356 INFO:usb.core:find(): using backend "usb.backend.libusb1"
2015-05-22 19:11:45,356 DEBUG:usb.backend.libusb1:_LibUSB.enumerate_devices()
2015-05-22 19:11:45,356 DEBUG:usb.backend.libusb1:_LibUSB.get_device_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06990>)
2015-05-22 19:11:45,357 DEBUG:usb.backend.libusb1:_LibUSB.get_device_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>)
2015-05-22 19:11:45,357 DEBUG:usb.backend.libusb1:_LibUSB.open_device(<usb.backend.libusb1._Device object at 0x7fef41e06a90>)
2015-05-22 19:11:45,358 DEBUG:usb.backend.libusb1:_LibUSB.is_kernel_driver_active(<usb.backend.libusb1._DeviceHandle object at 0x7fef4244df10>, 0)
2015-05-22 19:11:45,358 DEBUG:usb.backend.libusb1:_LibUSB.claim_interface(<usb.backend.libusb1._DeviceHandle object at 0x7fef4244df10>, 0)
2015-05-22 19:11:45,358 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0)
2015-05-22 19:11:45,359 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0, 0, 0)
2015-05-22 19:11:45,359 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0)
2015-05-22 19:11:45,359 DEBUG:usb.backend.libusb1:_LibUSB.get_endpoint_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0, 0, 0, 0)
2015-05-22 19:11:45,359 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0, 0, 0)
2015-05-22 19:11:45,359 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0)
2015-05-22 19:11:45,359 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration(<usb.backend.libusb1._DeviceHandle object at 0x7fef4244df10>)
2015-05-22 19:11:45,359 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0)
2015-05-22 19:11:45,360 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0, 0, 0)
2015-05-22 19:11:45,360 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0)
2015-05-22 19:11:45,360 DEBUG:usb.backend.libusb1:_LibUSB.get_endpoint_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0, 0, 0, 0)
2015-05-22 19:11:45,360 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0, 0, 0)
2015-05-22 19:11:45,360 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7fef41e06a90>, 0)
2015-05-22 19:11:45,360 DEBUG:usb.backend.libusb1:_LibUSB.claim_interface(<usb.backend.libusb1._DeviceHandle object at 0x7fef4244df10>, 0)
```

**Comment by Aswin21** [comment]
@walac 

I am using libmushu for gtting raw eeg access to my Emotiv epoc+ hardware. 

The relevant part of the program is given below:

	self.dev = usb.core.find(idVendor=VENDOR_ID, idProduct=PRODUCT_ID)
        
        # work unless i *don't* call it.
	if self.dev is None:
            raise RuntimeError('Emotiv device is not connected.')
        # pyusb docs say you *have* to call set_configuration, but it does not
        # work unless i *don't* call it.
        # get the serial number
	#self.dev.set_configuration()        
	serial = usb.util.get_string(self.dev, 17, self.dev.iSerialNumber)
        # claim the device and it's two interfaces
        if self.dev.is_kernel_driver_active(0):
            self.dev.detach_kernel_driver(0)
        usb.util.claim_interface(self.dev, 0)
        if self.dev.is_kernel_driver_active(1):
            self.dev.detach_kernel_driver(1)
        usb.util.claim_interface(self.dev, 1)

without calling the function dev.set_configuration()
I am getting an error:
Traceback (most recent call last):
  File "emotiv.py", line 173, in <module>
    amp = Epoc()
  File "emotiv.py", line 49, in __init__
    serial = usb.util.get_string(self.dev, 17, self.dev.iSerialNumber)
  File "/usr/local/lib/python2.7/dist-packages/usb/util.py", line 328, in get_string
    raise ValueError("The device does not support the specified langid")
ValueError: The device does not support the specified langid

The langid problem is solved when I am using dev.set_configuration()

But I am facing a new issue there, It gives the following error

Traceback (most recent call last):
  File "emotiv.py", line 171, in <module>
    amp = Epoc()
  File "emotiv.py", line 45, in __init__
    self.dev.set_configuration()
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 839, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 129, in managed_set_configuration
    self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 786, in set_configuration
    _check(self.lib.libusb_set_configuration(dev_handle.handle, config_value))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 592, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource bus

I need some assistance to solve the issue. I am really stuck with this problem.

**Comment by walac** [comment]
@Aswin21 You need to detach the kernel driver before issuing a `set_configuration`.

**Comment by Aswin21** [comment]
@walac I am really new to programming. Can you share some code or documentation regarding how to do that ?

**Comment by walac** [comment]
@Aswin21

**Comment by walac** [comment]
@Aswin21 This part of the code:

```python
    # claim the device and it's two interfaces
    if self.dev.is_kernel_driver_active(0):
        self.dev.detach_kernel_driver(0)
    usb.util.claim_interface(self.dev, 0)
    if self.dev.is_kernel_driver_active(1):
        self.dev.detach_kernel_driver(1)
    usb.util.claim_interface(self.dev, 1)
```

Should be moved before the `set_configuration` call.

**Comment by Aswin21** [comment]
@walac 

I am getting the same error no 16 "Resource busy" 

class Epoc(Amplifier):
	
    def __init__(self):
        # find amplifier
        self.dev = usb.core.find(idVendor=VENDOR_ID, idProduct=PRODUCT_ID)
        if self.dev is None:
            raise RuntimeError('Emotiv device is not connected.')
        # pyusb docs say you *have* to call set_configuration, but it does not
        # work unless i *don't* call it.  
        if self.dev.is_kernel_driver_active(0):
            self.dev.detach_kernel_driver(0)
        usb.util.claim_interface(self.dev, 0)
        if self.dev.is_kernel_driver_active(1):
            self.dev.detach_kernel_driver(1)
        usb.util.claim_interface(self.dev, 1)  
        
        self.dev.set_configuration()
        # get the serial number
        serial = usb.util.get_string(self.dev, 17, self.dev.iSerialNumber)
        # claim the device and it's two interfaces

**Comment by walac** [comment]
Could you please post logs? You can read how to generate the logs in the tutorial.

**Comment by Sam-Hall** [comment]
This should cure most "Resource busy" issues for newbies...
```
try:
  for cfg in device:
    for intf in cfg:
      if device.is_kernel_driver_active(intf.bInterfaceNumber):
        device.detach_kernel_driver(intf.bInterfaceNumber)
except usb.core.USBError as e:
  sys.exit("Could not detatch kernel driver from interface({0}): {1}".format(intf.bInterfaceNumber, str(e)))
```

**Comment by alexroot-** [comment]
Hello, it's been a while... @walac no, unfortunately not.
@Sam-Hall Thanks, will try that soon. But if I remember right, i've already tried something similar without success...

**Comment by Danisarts** [comment]
I have the same problem. Anyone has solution? Thanks. Dani

**Comment by rali717** [comment]
This solved it for me 
http://stackoverflow.com/questions/29345325/raspberry-pyusb-gets-resource-busy

**Comment by jmhuus** [comment]
FYI - my problem was fixed by unmounting the usb device.

**Comment by goncalor** [comment]
> This should cure most "Resource busy" issues for newbies...
> 
> ```
> for cfg in device:
>   for intf in cfg:
>     if device.is_kernel_driver_active(intf.bInterfaceNumber):
>       try:
>         device.detach_kernel_driver(intf.bInterfaceNumber)
>       except usb.core.USBError as e:
>         sys.exit("Could not detatch kernel driver from interface({0}): {1}".format(intf.bInterfaceNumber, str(e)))
> ```

@Sam-Hall just dropping a note that all these years later this comment greatly helped me troubleshoot the problem I was facing with "resource busy" errors. Thank you.
